var car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
var bike = 'honda';
console.log("Is bike == 'honda'? I predict True.");
console.log(bike == 'honda');
var airplane = 'jet';
console.log("Is airplane == 'jet'? I predict True.");
console.log(airplane == 'jet');
var boat = 'yacth';
console.log("Is boat == 'yacth'? I predict True.");
console.log(boat == 'yacth');
var mobile = 'iphone';
console.log("Is mobile == 'iphone'? I predict True.");
console.log(mobile == 'iphone');
var food = 'biryani';
console.log("Is food == 'biryani'? I predict True.");
console.log(food == 'mutton');
var drink = 'water';
console.log("Is drink == 'water'? I predict True.");
console.log(drink == 'cold drink');
var machine = 'laptop';
console.log("Is machine == 'computer'? I predict True.");
console.log(machine == 'computer');
var clothe = 'shirt';
console.log("Is clothe == 'shirt'? I predict True.");
console.log(clothe == 'jeans');
var bag = 'school bag';
console.log("Is bag == 'school bag'? I predict True.");
console.log(bag == 'school');
